name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e packages/mirrorengine -e packages/ribs

      - name: Install Node dependencies
        run: |
          cd apps/quickquote
          npm install
          cd ../..

      - name: Run tests
        run: |
          echo "Add tests here"
